name: Build container image
run-name: Build container image ${{ github.head_ref || github.sha }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
    uses: ./.github/workflows/build-workflow.yaml
    with:
      image-name: ${{ github.repository }}
      push: false
      platforms: linux/${{ matrix.arch }}
      upload-artifact: linux_${{ matrix.arch }}

  push:
    needs:
    - build
    uses: ./.github/workflows/build-workflow.yaml
    secrets:
      token: ${{ secrets.GH_PAT }}
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
      push: true
      platforms: linux/${{ matrix.arch }}
      upload-artifact: linux_${{ matrix.arch }}
      # - registry.hub.docker.com