name: Build container image
run-name: Build container image ${{ github.head_ref || github.sha }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       arch:
  #       - amd64
  #       - arm64
  #   uses: ./.github/workflows/build-workflow.yaml
  #   secrets:
  #     token: ${{ secrets.GH_PAT }}
  #   with:
  #     registry: ghcr.io
  #     image-name: ${{ github.repository }}
  #     push: true
  #     platforms: linux/${{ matrix.arch }}
  #     # outputs: type=docker,dest=/tmp/linux_${{ matrix.arch }}.tar
  #     # upload-artifact: /tmp/linux_${{ matrix.arch }}.tar

  # build-multi-architecture:
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GH_PAT }}
  #     - uses: docker/metadata-action@v4
  #       id: metadata
  #       with:
  #         images: ghcr.io/${{ github.repository }}
  #     - uses: int128/docker-manifest-create-action@v1
  #       with:
  #         tags: ${{ steps.metadata.outputs.tags }}
  #         suffixes: |
  #           -linux-amd64
  #           -linux-arm64

  build:
    uses: ./.github/workflows/build-workflow.yaml
    secrets:
      token: ${{ secrets.DOCKER_PAT }}
    with:
      image-name: patrykmalekkonghq/fork-build-test
      # image-name: ${{ github.repository }}
      push: true
      # outputs: type=docker,dest=/tmp/linux_${{ matrix.arch }}.tar
      # upload-artifact: /tmp/linux_${{ matrix.arch }}.tar

  # push:
  #   needs:
  #   - build
  #   uses: ./.github/workflows/build-workflow.yaml
  #   secrets:
  #     token: ${{ secrets.GH_PAT }}
  #   with:
  #     registry: ghcr.io
  #     image-name: ${{ github.repository }}
  #     push: true
  #     platforms: linux/${{ matrix.arch }}
  #     upload-artifact: linux_${{ matrix.arch }}
  #     # - registry.hub.docker.com